export const DEFAULT_MAX_PARTICLES = 1000;
export const MAX_PARTICLES_IN_A_SYSTEM = 5000;

export const PARTICLE_ORIENTATION_SCREEN_ALIGNED = 0;//Point towards camera
export const PARTICLE_ORIENTATION_SCREEN_Z_ALIGNED = 1;//parallel to camera axis
export const PARTICLE_ORIENTATION_WORLD_Z_ALIGNED = 2;
export const PARTICLE_ORIENTATION_ALIGN_TO_PARTICLE_NORMAL = 3;
export const PARTICLE_ORIENTATION_SCREENALIGN_TO_PARTICLE_NORMAL = 4;
export const PARTICLE_ORIENTATION_FULL_3AXIS_ROTATION = 5;
