

export const TEXTURE_FORMAT_UNKNOWN = 0;

export const TEXTURE_FORMAT_UNCOMPRESSED = 1 << 10;
export const TEXTURE_FORMAT_COMPRESSED_S3TC = 1 << 11;
export const TEXTURE_FORMAT_COMPRESSED_RGTC = 1 << 12;
export const TEXTURE_FORMAT_COMPRESSED_BPTC = 1 << 13;

export const TEXTURE_FORMAT_UNCOMPRESSED_RGB = TEXTURE_FORMAT_UNCOMPRESSED | 1;
export const TEXTURE_FORMAT_UNCOMPRESSED_RGBA = TEXTURE_FORMAT_UNCOMPRESSED | 2;
export const TEXTURE_FORMAT_UNCOMPRESSED_R8 = TEXTURE_FORMAT_UNCOMPRESSED | 3;
export const TEXTURE_FORMAT_UNCOMPRESSED_BGRA8888 = TEXTURE_FORMAT_UNCOMPRESSED | 4;

export const TEXTURE_FORMAT_COMPRESSED_RGB_DXT1 = TEXTURE_FORMAT_COMPRESSED_S3TC | 1;
export const TEXTURE_FORMAT_COMPRESSED_RGBA_DXT1 = TEXTURE_FORMAT_COMPRESSED_S3TC | 2;
export const TEXTURE_FORMAT_COMPRESSED_RGBA_DXT3 = TEXTURE_FORMAT_COMPRESSED_S3TC | 3;
export const TEXTURE_FORMAT_COMPRESSED_RGBA_DXT5 = TEXTURE_FORMAT_COMPRESSED_S3TC | 4;
export const TEXTURE_FORMAT_COMPRESSED_RGBA_BC4 = TEXTURE_FORMAT_COMPRESSED_RGTC | 1;
export const TEXTURE_FORMAT_COMPRESSED_RGBA_BC5 = TEXTURE_FORMAT_COMPRESSED_RGTC | 2;
export const TEXTURE_FORMAT_COMPRESSED_RGBA_BC7 = TEXTURE_FORMAT_COMPRESSED_BPTC | 1;
